name: Ci
on: [push]
jobs:
  standard-checks:
    name: Lint and Test
    runs-on: windows-2016

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci
      - name: Run Eslint
        run: npm run ci:lint
      - name: Run test
        run: npm run ci:test
    